### ISSUE TITLE
Cannot reconfigure

### ISSUE THREAD

**Issue by randyliugogoout** [launchdarkly/ld-vscode#118]
I want to reconfigure launchdarkly vscode extension. But it keep showing `Select a project`, how to solve this problem and continue to reconfigure?

<img width="717" alt="截圖 2024-02-17 中午12 16 09" src="https://github.com/launchdarkly/ld-vscode/assets/139094798/1deb1039-5a76-493a-a1e8-5821ad9fe824">

**Comment by InTheCloudDan** [comment]
Hi @randyliugogoout can you confirm which version you're on. If it is `5.0.0` can you try signing out of the Extension, in the lower left-hand corner of VSCode, clicking on the outline of the person, and then under LaunchDarkly, click `Sign Out` 
![CleanShot 2024-02-17 at 07 59 18@2x](https://github.com/launchdarkly/ld-vscode/assets/10308834/7e6876ad-7bca-42ba-8013-b13f05db6627)

After that you should be able to sign back in, but you will need your API token again.

**Comment by InTheCloudDan** [comment]
@randyliugogoout please re-open the issue if the suggestion above did not resolve the problem in the meantime I'll close this out.
