### ISSUE TITLE
Option to disable error when plugin settings fail to load

### ISSUE THREAD

**Issue by MartinNuc** [launchdarkly/ld-vscode#18]
I get this message everytime I open project which doesn't use LD therefore there is no settings for that.

![Screenshot 2019-11-05 at 15 00 09](https://user-images.githubusercontent.com/681176/68214309-78242200-ffdd-11e9-9177-0ed5f5e17064.png)

Would be great to suppress this warning when config is not set. I will probably try to create PR for that feature.

**Comment by atrakh** [comment]
Hi @MartinNuc,

Thank you for this suggestion. We've just released [2.1.2](https://github.com/launchdarkly/ld-vscode/releases/tag/2.1.2) which suppresses this message. Please update the extension at your earliest convenience.
