### ISSUE TITLE
Add support for a config file

### ISSUE THREAD

**Issue by CarloPalinckx** [launchdarkly/ld-vscode#19]
It would be great if there was support for a config file to set the extension's options. This way it can be versioned in a codebase which avoids every developer having to configure the extension.

**Comment by atrakh** [comment]
Hi @CarloPalinckx,

You may version your VSCode project settings by checking in `.vscode/settings.json` into version control. The `.vscode/settings.json` should automatically be created when you change your "workspace" settings. Please do take note that VSCode does not currently support variable values in your configuration (https://github.com/launchdarkly/ld-vscode/issues/15), so we'd advise against checking your LaunchDarkly SDK key into version control.

**Comment by atrakh** [comment]
Update: As of [2.2.0](https://github.com/launchdarkly/ld-vscode/releases), the `LaunchDarkly: Configure` command allows configuration of the extension without storing secrets in `settings.json`
