### ISSUE TITLE
Stop nagging user about configuration at startup

### ISSUE THREAD

**Issue by yozlet** [launchdarkly/ld-vscode#54]
When opening a VSCode project with the LD extension enabled but not configured, the extension displays a "select your desired environment" pop-up. It does this on every startup and it rapidly gets irritating, to the point where users will likely disable or even uninstall the extension.

I suggest:

1. don't request configuration unless the user **deliberately** invokes the extension in some way
2. when that invocation happens, put the configuration request where the user expects the result of the invocation, rather than an easily-missed corner pop-up. For example: if the user is opening the flag treeview, then the configuration request should go in the treeview panel.

**Comment by InTheCloudDan** [comment]
This should be resolved with the latest version.
