### ISSUE TITLE
Include tag support

### ISSUE THREAD

**Issue by JohnSigs** [launchdarkly/ld-vscode#98]
Feature request:

Would be very useful to be able to add a tag when creating a flag and also filter by tags in the Feature Flags panel.

**Comment by InTheCloudDan** [comment]
Thanks for the feedback @JohnSigs. Can you confirm which version of the IDE extension you are using? We did originally have `tags` as a required step when creating a boolean flag, but given the menu flow wanted to minimize the number of steps to create a flag to only what's required. 

Would it be helpful to be able to have a right-click menu option on the flag treeview to add/remove tags, or a separate command that can be accessed via command palette to add/remove them?
